//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblAbout
    {
        public int AboutId { get; set; }

        public string ImageUrl { get; set; }

        [Required(ErrorMessage = "Baþlýk boþ olamaz.")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Açýklama boþ olamaz.")]
        public string Description { get; set; }

        public string CvUrl { get; set; }
    }
}

